name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Install and Build
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
        run: |
          yarn install
          yarn run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.3.3
        with:
          branch: gh-pages
          folder: _site
