on:
  workflow_call:

jobs:
  lighthouse:
    name: Audit pages using lighthouse
    runs-on: ubuntu-latest

    steps:
      - name: Download generated site
        id: download_site
        uses: actions/download-artifact@v3
        with:
          name: site
          path: _site

      - name: Run Audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: "./lighthouserc.json"
          budgetPath: ./src/_includes/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
