name: pr
on: [pull_request]

jobs:
  linux:
    name: Linux build on node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up prerequisites - node and yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "16.11.1"
      - name: Set up yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build extension packages
        run: |
          cd extensions/eleventy-plugin-toc
          npm install

      - name: Install packages
        run: yarn install

      - name: Run Linting
        run: yarn run lint:check

      - name: Run Build
        run: yarn run build
