name: "[workflow] Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Linux build on node
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3.2.0

      - name: Set up prerequisites - node and yarn
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Cache yarn dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('yarn.lock') }}

      - name: Build extension packages
        run: |
          cd extensions/eleventy-plugin-toc
          npm install

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Spell Checking
        run: yarn run lint:spell

      - name: Run lint markdown
        run: yarn run lint:markdown

      - name: Run Linting
        run: yarn run lint:check

      - name: Run Build
        run: yarn run build

      - name: Audit pages using lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: "./lighthouserc.json"
          budgetPath: ./src/_includes/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Run pa11y
        run: yarn run pa11y-ci 2>&1 | tee pa11y_output.txt

      - name: Read pa11y_output file.
        id: pa11y_output
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pa11y_output.txt
        
      - name: Comment on pull request.
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: '<details><summary>Pa11y testing results</summary>```${{ steps.pa11y_output.outputs.content }}```</details>'

      - name: Check for pa11y failures.
        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
        run: |
          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
          exit 1
